---
policies:
  - type: commit
    spec:
      header:
        length: 200
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: false
      dco: false
      gpg: false
      spellcheck:
        locale: US
      maximumOfOneCommit: false
      exclude:
        - '^Merge branch.*'
        - '^Merge pull request.*'
      conventional:
        types:
          - refactor
          - chore
          - docs
          - feat
        scopes:
          - openapi
          - repository
          - service
          - controller
          - config
          - deps
          - ci
        descriptionLength: 100