package at.big5health.klimaatlas.dtos; // Or models

import lombok.Getter;

/**
 * Represents the various types of meteorological precipitation, typically
 * corresponding to values or classifications received from the Geosphere SPARTACUS
 * api endpoint.
 * <p>
 * Each enum constant defines a distinct form of precipitation. The associated
 * {@code message} field provides a human-readable string representation
 * (e.g., "rain", "snow") which might be the direct API string or a
 * standardized internal representation.
 * The {@link lombok.Getter} annotation provides a public {@code getMessage()} method.
 * <p>
 * It's important to ensure these enum values remain consistent and updated with the
 * possible values returned by the external API(s) this application interacts with.
 *
 * @see at.big5health.klimaatlas.httpclients.ExternalWeatherApiClient
 */
@Getter
public enum Precipitation {
    /**
     * Liquid water drops falling from clouds. Corresponds to an API value like "rain".
     */
    RAIN("rain"),
    /**
     * Light rain with very small water droplets. Corresponds to an API value like "drizzle".
     */
    DRIZZLE("drizzle"),
    /**
     * Frozen precipitation in the form of ice crystals. Corresponds to an API value like "snow".
     */
    SNOW("snow"),
    /**
     * A mixture of rain and snow or partially melted snow. Corresponds to an API value like "sleet".
     */
    SLEET("sleet"),
    /**
     * Solid precipitation in the form of balls or irregular lumps of ice. Corresponds to an API value like "hail".
     */
    HAIL("hail"),
    /**
     * Rain that freezes upon contact with surfaces at or below freezing point. Corresponds to an API value like "freezing rain".
     */
    FREEZING_RAIN("freezing rain"),
    /**
     * Drizzle that freezes upon contact with surfaces at or below freezing point. Corresponds to an API value like "freezing drizzle".
     */
    FREEZING_DRIZZLE("freezing drizzle"),
    /**
     * Small, translucent balls of ice. Corresponds to an API value like "ice pellets".
     */
    ICE_PELLETS("ice pellets"),
    /**
     * Soft, small pellets of ice. Corresponds to an API value like "graupel".
     */
    GRAUPEL("graupel"),
    /**
     * Indicates no precipitation occurred. Corresponds to an API value like "none" or absence of precipitation data.
     */
    NONE("none");

    /**
     * A string representation of the precipitation type, often matching or derived
     * from an external API's value. Suitable for display or logging.
     */
    private final String message;

    /**
     * Constructs a Precipitation enum constant with its descriptive message.
     *
     * @param message The string representation of the precipitation type,
     *                often related to an external API value.
     */
    Precipitation(String message) {
        this.message = message;
    }

    // getMessage() is automatically generated by Lombok's @Getter
}
