openapi: 3.0.0
servers:
  - url: https://api.big5health.at/backend
    description: Production Server
  - url: http://localhost:8080
    description: Staging Server
info:
  description: OpenAPI Specification for the Climate-Health Atlas Project
  version: "1.0.0"
  title: Atlas der Klima-bezogenen Gesundheitsrisiken API
  contact:
    name: Hochschule Burgenland Team
    email: 2310859039@hochschule-burgenland.at
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /dailyweather:
    get:
      tags:
        - dailyweather
      summary: Minimal, maximal temperature, precipitation, sunshine duration, coordinates for actual day.
      description: Get minimal and maximal temperature, precipitation, sunshine duration per kilometer for Austria originally from Spartacus for actual day.
      parameters:
        - name: cityName
          in: query
          schema:
            type: string
          required: true
          description: City name of the location
        - name: longitude
          in: query
          schema:
            type: number
            format: Double
          required: true
          description: Longitude of the Location
          example: 32.7
        - name: latitude
          in: query
          schema:
            type: number
            format: Double
            example: 32.7
          required: true
          description: Latitude of the Location
        - name: actualDate
          in: query
          schema:
            type: string
            format: date
          required: true
          description: Date for showing weather data (YYYY-MM-DD)
      responses:
        '200':
          description: Weather specific data in an object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  minTemp:
                    type: number
                    format: Double
                    example: 15.6
                  maxTemp:
                    type: number
                    format: Double
                    example: 32.7
                  precip:
                    type: string
                    enum: [ rain, drizzle, snow, sleet, hail, freezing rain, freezing drizzle, ice pellets, graupel, none ]
                    example: "rain"
                  sunDuration:
                    type: number
                    format: Double
                    example: "5.2"
                  latitude:
                    type: number
                    format: Double
                    example: 48.2082
                  longitude:
                    type: number
                    format: Double
                    example: 16.3738
        '400':
          description: Invalid request (e.g. post request)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid request"
        '500':
          description: Internal Server error (e.g. database failure)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Failed to fetch data from the database."
  /mosquito-alert:
    get:
      summary: Get mosquito alert data for a specific location
      parameters:
        - name: postalCode
          in: query
          schema:
            type: string
          required: false
          description: Postal code of the location
        - name: cityName
          in: query
          schema:
            type: string
          required: false
          description: City name of the location
        - name: startDate
          in: query
          schema:
            type: string
            format: date
          required: false
          description: Start date for filtering reports (YYYY-MM-DD)
        - name: endDate
          in: query
          schema:
            type: string
            format: date
          required: false
          description: End date for filtering reports (YYYY-MM-DD)
        - name: species
          in: query
          schema:
            type: string
          required: false
          description: Filter by mosquito species
        - name: riskLevel
          in: query
          schema:
            type: string
            enum: [ low, medium, high ]
          required: false
          description: Minimum risk level to filter results
      responses:
        '200':
          description: Mosquito alert data for the location
          content:
            application/json:
              schema:
                type: object
                properties:
                  region:
                    type: string
                  latitude:
                    type: number
                    format: float
                    description: Latitude of the affected region
                  longitude:
                    type: number
                    format: float
                    description: Longitude of the affected region
                  mosquitoSpecies:
                    type: array
                    items:
                      type: string
                    description: List of mosquito species reported in the region
                  alertLevel:
                    type: string
                    description: Risk level of mosquito activity (low, medium, high)
                  reportCount:
                    type: integer
                    description: Number of mosquito reports in the region
                  diseaseRisk:
                    type: array
                    items:
                      type: string
                    description: List of potential diseases carried by the detected mosquito species
                  lastReported:
                    type: string
                    format: date-time
                    description: Timestamp of the last reported mosquito sighting
                  trendAnalysis:
                    type: string
                    enum: [ increasing, stable, decreasing ]
                    description: Trend of mosquito reports over the last weeks
                  dataSources:
                    type: array
                    items:
                      type: string
                    description: Sources of the mosquito alert data
        '400':
          description: Invalid request
        '500':
          description: Server error
  /mosquito-occurrence:
    get:
      summary: Get mosquito occurrences in Austria
      description: Fetches mosquito occurrence data from GBIF API and returns coordinates
      responses:
        '200':
          description: A JSON array of mosquito occurrences
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "12345-abc"
                    latitude:
                      type: number
                      format: float
                      example: 48.2082
                    longitude:
                      type: number
                      format: float
                      example: 16.3738
                    stateProvince:
                      type: string
                      example: "Kaernten"
                    city:
                      type: string
                      example: "Wien"
                    date:
                      type: string
                      format: date
                      example: "2024-03-31"
                    species:
                      type: string
                      example: "insect"
                    source:
                      type: string
                      example: "GBIF"
        '400':
          description: Invalid request (e.g., missing or incorrect parameters)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid taxon key"
        '500':
          description: Internal Server error (e.g., GBIF API failure)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Failed to fetch data from GBIF"
