---
name: backend

on:
  pull_request:
    branches:
      - main

jobs:
  conform:
    runs-on: ubuntu-latest
    name: Conform

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - uses: siderolabs/conform@v0.1.0-alpha.27
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  check:
    runs-on: ubuntu-latest
    name: Check

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: PMD Check
        working-directory: backend
        run: |
          chmod +x ./gradlew
          ./gradlew clean pmdMain pmdTest

      - name: Checkstyle
        working-directory: backend
        run: |
          chmod +x ./gradlew
          ./gradlew clean checkstyleMain checkstyleTest

  build:
    runs-on: ubuntu-latest
    name: Build

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Test with Gradle
        working-directory: backend
        run: |
          chmod +x ./gradlew
          ./gradlew clean test

      - name: Build with Gradle
        working-directory: backend
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: spring-boot-jar
          path: backend/build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    name: Deployment
    needs: build

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Download artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: spring-boot-jar
#
#      - name: Deploy JAR to Server
#        uses: appleboy/scp-action@v0.1.4
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USER }}
#          key: ${{ secrets.SSH_KEY }}
#          source: "*.jar"
#          target: "/home/${{ secrets.SSH_USER }}/app/"
#
#      - name: Restart Application on Server
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USER }}
#          key: ${{ secrets.SSH_KEY }}
#          script: |
#            pkill -f 'java -jar' || true
#            nohup java -jar /home/${{ secrets.SSH_USER }}/app/*.jar > app.log 2>&1 &